# AUTO-GENERATED by infra/nix/deploy.sh from
#   tofu -chdir=infra/tofu output -raw data_volume_device
#
# Do not edit by hand — your changes will be overwritten on the next
# deploy. To change the volume, edit infra/tofu/volume.tf and apply.

{
  fileSystems."/srv/data" = {
    device = "/dev/disk/by-id/scsi-0HC_Volume_106477322";
    fsType = "ext4";
  };
}
