# AUTO-GENERATED by infra/nix/deploy.sh from
#   tofu -chdir=infra/tofu output -raw app_floating_ipv4
#
# Do not edit by hand — your changes will be overwritten on the next
# deploy.
#
# Binds the Hetzner Floating IPv4 as a secondary /32 on the public NIC
# after dhcpcd has configured the primary. `ip addr replace` is
# idempotent, so re-activation never trips on existing state.

{ pkgs, ... }:
{
  systemd.services.floating-ip = {
    description = "Bind Hetzner Floating IPv4 as secondary on enp1s0";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.iproute2}/bin/ip addr replace 159.69.100.198/32 dev enp1s0";
    };
  };
}
